# Generated by Django 4.2.15 on 2024-11-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landlord", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="number",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
